In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.mean([73,432,53,78,4])

128.0

In [5]:
np.median([73,432,53,78,4])

73.0

In [6]:
np.average([73,432,53,78,4])

128.0

In [7]:
l = [1,2,3,4,5]

In [9]:
d_1 = np.array(l)

In [10]:
d_1

array([1, 2, 3, 4, 5])

In [12]:
d_1.ndim #Direction

1

In [16]:
d_2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [17]:
d_2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [18]:
np.array([[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']])

array([['1', '2', '3', '4', '5'],
       ['10', '20', '30', '40', '50'],
       ['A', 'B', 'C', 'D', 'E']], dtype='<U11')

In [19]:
d_2.ndim

2

In [21]:
d_3 = np.array([[[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']]])

In [22]:
d_3

array([[['1', '2', '3', '4', '5'],
        ['10', '20', '30', '40', '50'],
        ['A', 'B', 'C', 'D', 'E']]], dtype='<U11')

In [23]:
d_3.ndim

3

In [26]:
d_1

array([1, 2, 3, 4, 5])

In [27]:
d_1[0]

1

In [28]:
np.random.randint(10,20,5)

array([17, 16, 14, 18, 15])

In [29]:
np.random.randint(1,5,10)

array([2, 2, 1, 4, 2, 4, 1, 3, 3, 1])

In [31]:
np.random.random(4)

array([0.41947967, 0.29348684, 0.02068606, 0.38518353])

In [32]:
np.random.rand(3,2)

array([[0.73404134, 0.10046376],
       [0.31060022, 0.96002995],
       [0.14059244, 0.83898071]])

In [33]:
np.random.rand(1,2)

array([[0.58475531, 0.19572338]])

In [35]:
np.random.rand(3,3)

array([[0.62056158, 0.93176926, 0.47495248],
       [0.84021446, 0.20994136, 0.70531862],
       [0.60042564, 0.26892457, 0.55051837]])